[package]
name = "labyrinth"
version = "0.1.0"
authors = ["Pepijn Dragt <pepijn.dragt@gmail.com>"]
edition = "2018"

[dependencies.labyrinth-engine]
path = "./labyrinth-engine"

[workspace]
members = [
  ".",
  "labyrinth-engine",
  "labyrinth-glyph",
  "labyrinth-obj",
  "labyrinth-cgmath"
]

[profile.release]
debug = false
lto = true
codegen-units = 1
